# Generated by Django 5.2.1 on 2025-05-29 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("image", models.URLField()),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
