# Generated by Django 5.2.1 on 2025-06-03 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0003_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="average_rating",
            field=models.FloatField(default=0.0),
        ),
    ]
