# Generated by Django 5.2.1 on 2025-06-06 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0007_handbag_handbagrating"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="wishlist",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="wishlist",
            name="handbags",
            field=models.ManyToManyField(
                blank=True, related_name="wishlisted_by", to="app1.handbag"
            ),
        ),
        migrations.AddField(
            model_name="wishlist",
            name="products",
            field=models.ManyToManyField(
                blank=True, related_name="wishlisted_by", to="app1.product"
            ),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wishlist",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="wishlist",
            name="added_at",
        ),
        migrations.RemoveField(
            model_name="wishlist",
            name="product",
        ),
    ]
