# Generated by Django 5.2.1 on 2025-06-09 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0008_alter_wishlist_unique_together_wishlist_handbags_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("image", models.ImageField(upload_to="service_images/")),
                ("average_rating", models.FloatField(default=0.0)),
            ],
        ),
    ]
