# Generated by Django 5.2.1 on 2025-06-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0009_service"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("hairdressing", "Hairdressing"),
                            ("barber", "Barber"),
                            ("nails", "Nails"),
                            ("manicure", "Manicure"),
                            ("pedicure", "Pedicure"),
                        ],
                        max_length=20,
                    ),
                ),
                ("image", models.ImageField(upload_to="gallery/")),
                ("description", models.CharField(blank=True, max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
