# Generated by Django 5.2.1 on 2025-06-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0010_galleryimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="offers/")),
                ("description", models.TextField()),
                ("offer_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
