# Generated by Django 5.2.1 on 2025-06-17 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0012_userprofile_added_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rating",
            name="rating",
        ),
        migrations.AddField(
            model_name="rating",
            name="value",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Rate between 1 (worst) and 5 (best)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
