# Generated by Django 5.2.1 on 2025-06-22 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0013_remove_rating_rating_rating_value"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="galleryimage",
            name="image",
        ),
        migrations.AddField(
            model_name="galleryimage",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="gallery/"),
        ),
    ]
