# Generated by Django 5.2.1 on 2025-06-22 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0014_remove_galleryimage_image_galleryimage_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service",
            old_name="description",
            new_name="full_description",
        ),
        migrations.AddField(
            model_name="service",
            name="short_description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="service",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="services/"),
        ),
    ]
