# Generated by Django 5.2.1 on 2025-07-15 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0015_rename_description_service_full_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="handbag",
            name="average_rating",
        ),
    ]
