# Generated by Django 5.2.1 on 2025-07-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0016_remove_handbag_average_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="handbag",
            name="average_rating",
            field=models.FloatField(default=0.0),
        ),
    ]
