# Generated by Django 4.2.23 on 2025-09-22 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_cashflow_gallerylike_inventorytransaction_sale_and_more'),
        ('app1', '0020_gallerylike'),
    ]

    operations = [
    ]
