# Generated by Django 5.2.1 on 2025-11-04 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_clothes'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='clothes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.clothes'),
        ),
        migrations.AddField(
            model_name='sale',
            name='clothes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.clothes'),
        ),
    ]
