# Generated by Django 5.2.1 on 2026-06-02 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_count', models.PositiveIntegerField(default=1, help_text='Max simultaneous bookings (= number of workers)')),
                ('slot_duration_minutes', models.PositiveIntegerField(default=30, help_text='Appointment duration in minutes')),
                ('start_time', models.TimeField(default='08:00')),
                ('end_time', models.TimeField(default='20:00')),
                ('active_days', models.JSONField(default=list, help_text='Active weekdays (0=Mon, 5=Sat, 6=Sun)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slot_config', to='app1.service')),
            ],
            options={
                'ordering': ['service__name'],
            },
        ),
    ]
