# Generated by Django 5.2.13 on 2026-06-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0030_password_change_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="bio",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
