# Generated by Django 5.2.1 on 2026-06-15 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0031_userprofile_avatar_userprofile_bio_userprofile_phone'),
        ('app1', '0032_set_dr_rashel_featured'),
    ]

    operations = [
    ]
