# Generated by Django 5.2.1 on 2026-06-16 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0033_merge_20260615_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='handbag',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='clothes_images/'),
        ),
        migrations.AlterField(
            model_name='handbag',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='handbag_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
