# Generated by Django 5.2.15 on 2026-09-30 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0037_luxuryitem_luxuryinquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='shop',
            field=models.CharField(blank=True, choices=[('beauty', 'Beauty'), ('fashion', 'Fashion'), ('luxury', 'Luxury')], max_length=20, null=True),
        ),
    ]
