# Generated by Django 5.2.15 on 2026-09-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0038_cashflow_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='shop',
            field=models.CharField(choices=[('beauty', 'Beauty'), ('fashion', 'Fashion'), ('luxury', 'Luxury')], default='beauty', max_length=20),
        ),
    ]
