# Generated by Django 5.2.15 on 2026-09-30 19:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0039_galleryimage_shop'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'clothes categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='shop',
            field=models.CharField(blank=True, choices=[('beauty', 'Beauty'), ('fashion', 'Fashion')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='shop',
            field=models.CharField(blank=True, choices=[('beauty', 'Beauty'), ('fashion', 'Fashion')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='shop',
            field=models.CharField(choices=[('beauty', 'Beauty'), ('fashion', 'Fashion')], default='beauty', max_length=20),
        ),
        migrations.AddField(
            model_name='clothes',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clothes', to='app1.clothescategory'),
        ),
        migrations.CreateModel(
            name='ServiceSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('card', 'Card'), ('other', 'Other')], default='cash', max_length=10)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('served_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='app1.service')),
            ],
            options={
                'ordering': ['-served_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='cashflow',
            name='reference_service_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.servicesale'),
        ),
        migrations.DeleteModel(
            name='LuxuryInquiry',
        ),
        migrations.DeleteModel(
            name='LuxuryItem',
        ),
    ]
