# Generated by Django 5.2.15 on 2026-10-02 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0045_saleedit'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='handbag',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
