# Generated by Django 5.2.15 on 2026-10-02 02:08

import django.utils.timezone
from django.db import migrations, models


def backfill_date_purchased(apps, schema_editor):
    """Existing rows were dated by when they were entered; keep that (in shop-local time)."""
    Expense = apps.get_model('app1', 'Expense')
    for expense in Expense.objects.all().only('id', 'created_at'):
        Expense.objects.filter(pk=expense.pk).update(date_purchased=django.utils.timezone.localtime(expense.created_at).date())


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0046_price_range'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date_purchased', '-created_at']},
        ),
        migrations.AddField(
            model_name='expense',
            name='date_purchased',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.RunPython(backfill_date_purchased, migrations.RunPython.noop),
    ]
