# Generated by Django 5.2.15 on 2026-10-02 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0048_expense_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(db_index=True, max_length=30)),
                ('object_ref', models.PositiveIntegerField()),
                ('object_label', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(choices=[('edit', 'Edit'), ('delete', 'Delete')], max_length=10)),
                ('actor_username', models.CharField(max_length=150)),
                ('before', models.JSONField(null=True)),
                ('after', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['kind', 'object_ref'], name='app1_audite_kind_f15304_idx')],
            },
        ),
    ]
